name: Backend Test
on:
   push:
      branches: [ main ]
   pull_request:
jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [24.x, 19.x, 18.x]
    defaults:
      run:
        working-directory: backend
    steps:
      - name: setup
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: Run All tests
        run: npm run test
